### ISSUE TITLE
Just add server-side checking for lengths rather than client-side ones

### ISSUE THREAD

**Issue by PPPDUD** [jeffalo/my-ocular#40]
^

**Comment by jeffalo** [comment]
resolved in #39

**Comment by PPPDUD** [comment]
Nope, that's client-side.

**Comment by return-misaPuding** [comment]
I think it needs to be in my-ocular to be serverside and therefore #39 didn't solve this?

**Comment by PPPDUD** [comment]
> I think it needs to be in my-ocular to be serverside and therefore #39 didn't solve this?

Yes.

**Comment by jeffalo** [comment]
#39 solves it. this is my-ocular
